version: 0.2.3.{build}

before_build:
  - ps: appveyor\UpdateBuildVersion.ps1

build:
  project: msbuild\ReleaseTestAndRelease.proj
  verbosity: minimal

test_script:
  - vstest.console /logger:Appveyor bin/Release_Tests/UnitTests.dll

on_success:
  - ps: appveyor\PrepareNewBuildVersion.ps1

artifacts:
  - path: bin\Release
    name: LightFX-Extender-v$(appveyor_build_version)
    type: zip

deploy:
  provider: GitHub
  auth_token:
    secure: fHXemLwKHEg/6UXe2alr3/fUlPoZrNLmIsWgErk4u7vjCgMKGHYys+msNct3REOY
  artifact: bin\LightFX-Extender-v$(appveyor_build_version).zip
  on:
    appveyor_repo_tag: true

environment:
  access_token: fHXemLwKHEg/6UXe2alr3/fUlPoZrNLmIsWgErk4u7vjCgMKGHYys+msNct3REOY
