version: 0.5.2.{build}

environment:
  access_token:
    secure: fHXemLwKHEg/6UXe2alr3/fUlPoZrNLmIsWgErk4u7vjCgMKGHYys+msNct3REOY

platform:
  - x86
  - x64
  - release

matrix:
  fast_finish: true


install:
  - ps: appveyor\InstallDependencies.ps1

before_build:
  - ps: appveyor\UpdateBuildVersion.ps1

build:
  project: appveyor\Build_$(platform).proj
  verbosity: minimal

after_build:
  - ps: appveyor\PackageArtifacts.ps1

test_script:
  - ps: appveyor\Test.ps1

on_success:
  - ps: appveyor\PrepareNewBuildVersion.ps1


artifacts:
  - path: artifacts\*.*
    name: LightFX Extender v$(appveyor_build_version)-$(platform)

deploy:
  provider: GitHub
  auth_token:
    secure: fHXemLwKHEg/6UXe2alr3/fUlPoZrNLmIsWgErk4u7vjCgMKGHYys+msNct3REOY
  artifact: /artifacts\\.*/
  draft: true
  on:
    appveyor_repo_tag: true
    platform: release
