version: 0.0.{build}

configuration: Release

before_build:
  - ps: appveyor/UpdateBuildVersion.ps1

artifacts:
  - path: bin/$(configuration)
    name: LightFX Extender v$(appveyor_build_version)
    type: zip
