version: 0.0.{build}

configuration: Release

before_build:
  - ps: appveyor/UpdateBuildVersion.ps1

test:
  - vstest.console /logger:Appveyor bin/test/%CONFIGURATION%/UnitTests.dll

artifacts:
  - path: bin/$(configuration)
    name: LightFX Extender v$(appveyor_build_version)
    type: zip
